### ISSUE TITLE
二次开发

### ISSUE THREAD

**Issue by DDullahan** [edboffical/bsp#32]
谢谢 @edboffical 开源的bsp

最近有幸使用bsp，ss多用户管理很便利。可以说是功能很全，又很轻量级的管理包了 :thumbsup:

但是在使用的过程中遇到了一些问题，在其他的issues中也有提到，所以希望在bsp的基础上二次开发

我会注明二次开发的来源 ，您也可以关注我的进程，期待您的PR :laughing:

**Comment by edboffical** [comment]
加油
