### ISSUE TITLE
centos7无法正常使用

### ISSUE THREAD

**Issue by huaiyizhao** [edboffical/bsp#5]
fiewalls配置和limit文件配置会互相覆盖，请问能修改一下发布一个centos7能用的版本吗

**Comment by edboffical** [comment]
不好意思现在才看到 可以具体说下问题吗

**Comment by huaiyizhao** [comment]
Centos7的防火墙用的firewall的配置，byte_lib.py中add_rules 里用的是iptables的命令。我运行脚本之后需要再添加firewalls的开启端口的命令，但开启之后统计流量等一些功能就不能用了。再次运行脚本，端口貌似又无法开放了。我在add_rules 里吧iptables的命令改成firewalls的命令但好像执行不了，有兴趣的话您可以了解一下，修改成一个centos6和7通用的版本。
