### ISSUE TITLE
ubuntu16.04下使用异常

### ISSUE THREAD

**Issue by nch14** [edboffical/bsp#6]
使用默认的apt-get获得的python(2.7)
已经正确配置文件

root@vultr:~# bsp -p 8989 -P 123456 -j
Traceback (most recent call last):
  File "/usr/bin/bsp", line 32, in <module>
    byte_lib.a_json(ss_port,ss_pwd)
  File "/usr/bin/byte_lib.py", line 73, in a_json
    data['port_password'][port] = pwd
KeyError: 'port_password'

请求帮忙看一下～

**Comment by nch14** [comment]
发现因为ss的配置没有修改。我的锅

**Comment by PointerWild** [comment]
可以问一下，怎么配这个ss? 我也出现了这个问题。我用的  shadowshocks-go    .
