### ISSUE TITLE
无法重启

### ISSUE THREAD

**Issue by tsgkim** [edboffical/bsp#8]
我的 ss 启动命令是 ssserver -c /etc/shadowsocks.json -d restart
但是我在byte_ss.json配置为：
{
    "ssconf_path":"/etc/shadowsocks-python/config.json",
    "ress_cmd":"ssserver -c  /etc/shadowsocks-python/config.json -d restart",
    "update_time":"60",
    "port_limit": {
    }
} 
或者配置为：
{
    "ssconf_path":"/etc/shadowsocks-python/config.json",
    "ress_cmd":"/etc/shadowsocks-python/config.json -d restart",
    "update_time":"60",
    "port_limit": {
    }
} 
都无法重启  账号是可以删除

**Comment by edboffical** [comment]
就是说删除了之后 没有重启生效 被删除的账户还能用？

**Comment by y7y8123456** [comment]
我也是这个问题，账号会删除但不会自动重启，要手打一遍qwq
